### ISSUE TITLE
seek help in building SequenceR docker image

### ISSUE THREAD

**Issue by jaxxgu** [KTH/sequencer#2]
Following the README, I can build the SequenceR docker image. However, during the process, Torch lib can never be installed successfully. Then "sequencer-predict.sh" would always interrupted at [L115](https://github.com/KTH/sequencer/blob/master/src/sequencer-predict.sh#L115) because of "ImportError: No module named 'torch'".

Has this ever appended in your experiments before? If not and you still have the environment. Could you please release one golden image to Docker Hub?

If you can release one docker image to hub, here are commands:
```
docker build --tag=sequencer .
docker tag sequencer xxxxxx/sequencer:1.0
docker login
docker push xxxxxx/sequencer:1.0
```

Thanks in advance.

**Comment by jaxxgu** [comment]
I build the SequenceR golden image successfully, here is [one released image](https://cloud.docker.com/repository/docker/ycaxgjd/sequencer), in case someone is seeking

**Comment by jaxxgu** [comment]
I made one PR #3 to solve strange issues occurred in building golden image and invoking SequenceR.

**Comment by chenzimin** [comment]
Reopen because of questions in https://github.com/KTH/sequencer/pull/3

**Comment by chenzimin** [comment]
When we encountered problem of building the docker images with the following error message:
```
Collecting torch>=1.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/30/57/d5cceb0799c06733eefce80c395459f28970ebb9e896846ce96ab579a3f1/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (748.8MB)
./src/setup_env.sh: line 58:    38 Killed                  pip3 install -r requirements.txt
```

The solution is to increase docker RAM.

**Comment by chenzimin** [comment]
@jaxxgu I assume that you can build the image now, what more problem are you facing now?

**Comment by jaxxgu** [comment]
Hey @chenzimin 
Actually I can build one SequenceR image and have it work normally. I was asked to make one PR in case others can not build image successfully with current repo. I personally do not have difficulties, and do not care too much about which way we use to build one effective image. You do not have to spend time here. If everything is okay, you could just close my PR directly. If convenient, could you please release one official golden image to docker hub?

**Comment by chenzimin** [comment]
Close issues as we have image on docker hub now.
