### ISSUE TITLE
Where is the training and testing dataset for SequenceR?

### ISSUE THREAD

**Issue by code-rex1** [KTH/sequencer#40]
Can you please point me to the direction from where can I download the dataset for SequenceR?

The paper mentioned:

```
In our experiments, we combine two sources of past commits, the CodRep dataset [33] and the Bugs2Fix dataset [10], into what appears to be the largest dataset of one-line bug fixes published to date.
```

Have you compiled these two dataset sources and provide as a artefact?

**Comment by monperrus** [comment]
See Section `Experiments` of the README:

> The training data consists of results/Golden/src-train.txt and results/Golden/tgt-train.txt (line to line correspondence).
