### ISSUE TITLE
What is the token seq2seq4repair_space?

### ISSUE THREAD

**Issue by code-rex1** [KTH/sequencer#41]
I see `seq2seq4repair_space` repeated over and over again the dataset files. 

For example, entries from `tgt-train.txt`:

```
assertTextPresent ( "This<seq2seq4repair_space>example<seq2seq4repair_space>displays<seq2seq4repair_space>how<seq2seq4repair_space>you<seq2seq4repair_space>can<seq2seq4repair_space>work<seq2seq4repair_space>with<seq2seq4repair_space>'nice'<seq2seq4repair_space>urls<seq2seq4repair_space>for<seq2seq4repair_space>bookmarkable<seq2seq4repair_space>pages." ) ;
...
builder . append ( ( ( "\'id\':<seq2seq4repair_space>\"" + ( getJsId ( ) ) ) + "\"," ) ) ;
```

What this token is intended for?

**Comment by monperrus** [comment]
`<seq2seq4repair_space>` (with the `<` and `>`) is a special encoding token, it encodes a non tokenized space.

`"\'id\':<seq2seq4repair_space>\"" + (` is three tokens (all separated by space), the first token should be interpreted `"\'id\':\""`.
